### ISSUE TITLE
taggable form element doctrine hydration

### ISSUE THREAD

**Issue by nuvolaTeam** [hilobok/doctrine-extensions-taggable#4]
Hi all,
I am trying to insert into a form hydrated with doctrineObject a field for tag insertion using taggable extension, but it is not clear at all how to accomplish this.

**Comment by hilobok** [comment]
Can you explain in details what you are trying to accomplish?

**Comment by nuvolaTeam** [comment]
Dear Andrew,
I have installed and configured the taggable extensions as instructions say. I have a doctrine entity with ORM annotation with the getTaggableType configured and implementing TaggableInterface and extending AbstractTaggable. The abstract class AbstractTaggable gives me the tags property.
I created a form with Zend, hydrated with DoctrineObject, and created an objectSelect for the tags property. The problem is that the doctrine hydrator doesn't work, i believe, because tha tags property in my entty is not doctrine mapped with annotation, so the tags stored in the db are not visualized as selected and when I try to save the form i obtain "setTags" first argument must be a collection, array given. It seems that the extension wants zend hydrator, and in fact creating a form only for tags with zend classmethod hydrator all seems to work. But I need doctrine hydrator.
I hope to have been clear, in case not I will try to post an example.

Many thanks Andrew

**Comment by hilobok** [comment]
If I understand you correctly it's not possible at the moment, because entity not associated with its tags via doctrine. Extension just helps to add/fetch corresponding tags. This feature planned for next major release but it's far from implementation yet.
