### ISSUE TITLE
Doctrine 2.5

### ISSUE THREAD

**Issue by plfort** [hilobok/doctrine-extensions-taggable#5]
Does this extension work with doctrine ORM 2.5 or doctrine common 2.5 ?
I use doctrine 2.4.* in my composer.json but it installs doctrine common 2.5 and it is not compatible with your requirements (<2.5 for orm and common)

**Comment by hilobok** [comment]
Its dependency [doctrine-extensions-resource](https://github.com/hilobok/doctrine-extensions-resource) is not compatible with ORM 2.5 currently, so I assume that short answer is no. I'll try to find some time to fix this in next couple of days.

**Comment by hilobok** [comment]
Done. It should work with Doctrine 2.5 now. Feel free to reopen if something pops up.
